resources:
  - apigateway.yaml
  - auth.yaml
  - dw-approval.yaml
  - gpc-ui-service.yaml
  - hr-benefit-pv.yaml
  - hr-benefit-pvc.yaml
  - hr-ess-attendance.yaml
  - hr-ess-benefit.yaml
  - hr-ess-employee.yaml
  - hr-ess-employment.yaml
  - hr-ess-image.yaml
  - hr-ess-performanceappraisal.yaml
  - hr-ess-profile.yaml
  - hr-ess-timeattendance.yaml
  - hr-ess-utility.yaml
  - hr-utility-pvc.yaml
  - hr-ess-recruitmentorder-service.yaml
  - hr-ess-publicapi-service.yaml
  - hr-ess-todo-mq-service.yaml
  - hr-ess-fixedasset-service.yaml
